name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            .build/artifacts
            .build/checkouts
            .build/repositories
          key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.resolved') }}

      - name: Get Swift Version
        run: swift --version

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
